services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports: ["27017:27017"]
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  # optional .js/.sh init scripts
volumes:
  mongo_data:
