services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strong_admin_password
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  # optional .js/.sh init scripts
volumes:
  mongo_data:
